[build]
  publish = "/"
  # No build command needed for static site.

# Add basic headers to improve caching
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 